app = "green-wildflower-1633"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
